set -g status-bg "#eb6894"
set -g status-fg "#000000"
set -g window-status-style fg="#000000"
set -g window-status-current-style fg="#000000"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
